package fr.vbillard.tissusdeprincesseboot.controller.utils.path;

import lombok.Getter;

@Getter
public enum PathEnum {
  ROOT, TISSUS, TISSUS_CARD, TISSUS_DETAILS, TISSUS_EDIT, PROJET_LIST, PROJET_DETAILS, PROJET_EDIT, PROJET_CARD,
  PATRON_LIST, PATRON_DETAILS, PATRON_EDIT, PATRON_CARD, MATIERE, TISSAGE, TISSU_REQUIS,
  PROJET_EDIT_TISSU_LIST_ELEMENT, PROJET_EDIT_FOURNITURE_LIST_ELEMENT, TISSU_USED_CARD, TISSU_REQUIS_SELECTED,
  PLUS_CARD, SET_LONGUEUR, WEB_URL, TISSU_SEARCH, CHECKBOX_CHOICE, PATRON_SEARCH, PROJET_SEARCH, PREF, CARROUSEL,
  INVENTAIRE, FOURNITURES, FOURNITURES_CARD, FOURNITURES_DETAILS, FOURNITURES_EDIT, FOURNITURE_USED_CARD,
  FOURNITURE_REQUIS_SELECTED, FOURNITURE_CARROUSEL, TYPE_FOURNITURE, FOURNITURE_SEARCH, FOURNITURE_REQUIS_CARD,
  SET_QUANTITE,PATRON_VERSION_ACCORDION, TISSU_REQUIS_ACCORDION, FOURNITURE_REQUISE_ACCORDION,
  PATRON_EDIT_PATRON_VERSION, PATRON_EDIT_PATRON, PATRON_EDIT_FOURNITURE_REQUISE, PATRON_EDIT_TISSU_REQUIS, 
  PATRON_DETAIL_TISSU_DISPLAY, PATRON_DETAIL_VERSION_DISPLAY, RANGEMENT_TREE, RANGEMENTS_MODALE, TISSU_SELECTED, PATRON_SELECTED, FOURNITURE_SELECTED
}
