package fr.vbillard.tissusdeprincesseboot.utils.path;

import lombok.Getter;

@Getter
public enum PathEnum {
	ROOT, TISSUS, TISSUS_CARD, TISSUS_DETAILS, TISSUS_EDIT, PROJET_LIST, PROJET_DETAILS, PROJET_EDIT, PROJET_CARD,
	PATRON_LIST, PATRON_DETAILS, PATRON_EDIT, PATRON_CARD, MATIERE, TISSAGE, LIST_ELEMENT, TISSU_REQUIS,
	PROJET_EDIT_LIST_ELEMENT, TISSU_USED_CARD, TISSU_REQUIS_SELECTED, PLUS_CARD, SET_LONGUEUR, WEB_URL, TISSU_SEARCH,
	CHECKBOX_CHOICE, PATRON_SEARCH, PROJET_SEARCH, PREF, CARROUSEL, INVENTAIRE

}
